export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_UNAUTHORIZED = 'LOGIN_UNAUTHORIZED';
export const LOGOUT = 'LOGOUT';

export const FETCH_FORNECEDORES_REQUEST = 'FETCH_FORNECEDORES_REQUEST';
export const FETCH_FORNECEDORES_SUCCESS = 'FETCH_FORNECEDORES_SUCCESS';
export const FETCH_FORNECEDORES_FAILURE = 'FETCH_FORNECEDORES_FAILURE';

export const FETCH_FORNECEDOR_REQUEST = 'FETCH_FORNECEDOR_REQUEST';
export const FETCH_FORNECEDOR_SUCCESS = 'FETCH_FORNECEDOR_SUCCESS';
export const FETCH_FORNECEDOR_FAILURE = 'FETCH_FORNECEDOR_FAILURE';

export const FETCH_DUPLICATAS_REQUEST = 'FETCH_DUPLICATAS_REQUEST';
export const FETCH_DUPLICATAS_SUCCESS = 'FETCH_DUPLICATAS_SUCCESS';
export const FETCH_DUPLICATAS_FAILURE = 'FETCH_DUPLICATAS_FAILURE';

export const FETCH_ABATIMENTOS_REQUEST = 'FETCH_ABATIMENTOS_REQUEST';
export const FETCH_ABATIMENTOS_SUCCESS = 'FETCH_ABATIMENTOS_SUCCESS';
export const FETCH_ABATIMENTOS_FAILURE = 'FETCH_ABATIMENTOS_FAILURE';

export const GET_LIMITS_REQUEST = 'GET_LIMITS_REQUEST';
export const GET_LIMITS_SUCCESS = 'GET_LIMITS_SUCCESS';
export const GET_LIMITS_FAILURE = 'GET_LIMITS_FAILURE';

export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';

export const SEND_MAIL_NOTAS_REQUEST = 'SEND_MAIL_NOTAS_REQUEST';
export const SEND_MAIL_NOTAS_SUCCESS = 'SEND_MAIL_NOTAS_SUCCESS';
export const SEND_MAIL_NOTAS_FAILURE = 'SEND_MAIL_NOTAS_FAILURE';